// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIRny7dQ2UlKvrnNSpXzKq2fzcLrpdAhg',
    appId: '1:797831544947:web:c96e51f47aad0efd962a06',
    messagingSenderId: '797831544947',
    projectId: 'internship-ee68d',
    authDomain: 'internship-ee68d.firebaseapp.com',
    storageBucket: 'internship-ee68d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-VxsXx1gNawnYhEH2IpLGCX_25dqfeLs',
    appId: '1:797831544947:android:12e288c3e1a504bd962a06',
    messagingSenderId: '797831544947',
    projectId: 'internship-ee68d',
    storageBucket: 'internship-ee68d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClWFpH2ul2CGM7vmNedwrGV50xCoPTI5A',
    appId: '1:797831544947:ios:5053cd019d11ee77962a06',
    messagingSenderId: '797831544947',
    projectId: 'internship-ee68d',
    storageBucket: 'internship-ee68d.firebasestorage.app',
    androidClientId: '797831544947-19k9ntv8nohs18pgdjh37847ua4cr9a0.apps.googleusercontent.com',
    iosClientId: '797831544947-1kkmbg3e3eenvk5kdhh3eha2ua8f9lup.apps.googleusercontent.com',
    iosBundleId: 'com.example.arogyarakshaAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClWFpH2ul2CGM7vmNedwrGV50xCoPTI5A',
    appId: '1:797831544947:ios:5053cd019d11ee77962a06',
    messagingSenderId: '797831544947',
    projectId: 'internship-ee68d',
    storageBucket: 'internship-ee68d.firebasestorage.app',
    androidClientId: '797831544947-19k9ntv8nohs18pgdjh37847ua4cr9a0.apps.googleusercontent.com',
    iosClientId: '797831544947-1kkmbg3e3eenvk5kdhh3eha2ua8f9lup.apps.googleusercontent.com',
    iosBundleId: 'com.example.arogyarakshaAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIRny7dQ2UlKvrnNSpXzKq2fzcLrpdAhg',
    appId: '1:797831544947:web:39c9fe168bfe9368962a06',
    messagingSenderId: '797831544947',
    projectId: 'internship-ee68d',
    authDomain: 'internship-ee68d.firebaseapp.com',
    storageBucket: 'internship-ee68d.firebasestorage.app',
  );

}